# Exploring `gym-anytrading`

### Imports and Setup

In [1]:
# Gym stuff
import gym
import gym_anytrading

# Processing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
env = gym.make('stocks-v0', frame_bound=(50,2000), window_size=10)

In [6]:
env.df

Open         High          Low        Close    Adj Close  \
Date                                                                          
2009-05-22   198.528534   199.524521   196.196198   196.946945   196.946945   
2009-05-26   196.171173   202.702698   195.195190   202.382385   202.382385   
2009-05-27   203.023026   206.136139   202.607605   202.982986   202.982986   
2009-05-28   204.544540   206.016022   202.507507   205.405411   205.405411   
2009-05-29   206.261261   208.823822   205.555557   208.823822   208.823822   
...                 ...          ...          ...          ...          ...   
2018-08-23  1219.880005  1235.170044  1219.349976  1221.160034  1221.160034   
2018-08-24  1226.000000  1237.400024  1221.420044  1236.750000  1236.750000   
2018-08-27  1244.140015  1257.869995  1240.680054  1256.270020  1256.270020   
2018-08-28  1255.900024  1256.560059  1242.969971  1245.859985  1245.859985   
2018-08-29  1255.000000  1267.170044  1252.800049  1264.650024  1264.650024   

             Volume  
Date                 
2009-05-22  3433700  
2009-05-26  6202700  
2009-05-27  6062500  
2009-05-28  5332200  
2009-05-29  5291100  
...             ...  
2018-08-23  1233300  
2018-08-24  1222700  
2018-08-27  1429000  
2018-08-28  1366500  
2018-08-29  1846300  

[2335 rows x 6 columns]

In [25]:
prices = env.prices
print(prices)

[214.164169 214.059052 218.888885 ... 924.52002  932.820007 937.090027]


In [27]:
# Prices goes from index framebound[0]-window_size to framebound[1]
all(prices == env.df['Adj Close'].to_numpy()[40:2000])

True

In [36]:
print(env.signal_features) # prices and price differences

len(prices), len(env.signal_features)

[[ 2.14164169e+02  0.00000000e+00]
 [ 2.14059052e+02 -1.05117000e-01]
 [ 2.18888885e+02  4.82983300e+00]
 ...
 [ 9.24520020e+02  3.30800180e+01]
 [ 9.32820007e+02  8.29998700e+00]
 [ 9.37090027e+02  4.27002000e+00]]


(1960, 1960)

In [34]:
len(prices), len(env.signal_features)

(1960, 1960)

In [37]:
env.reset()

array([[ 2.14059052e+02, -1.05117000e-01],
       [ 2.18888885e+02,  4.82983300e+00],
       [ 2.23583588e+02,  4.69470300e+00],
       [ 2.22622620e+02, -9.60968000e-01],
       [ 2.20145142e+02, -2.47747800e+00],
       [ 2.18338333e+02, -1.80680900e+00],
       [ 2.23043045e+02,  4.70471200e+00],
       [ 2.21746750e+02, -1.29629500e+00],
       [ 2.26331329e+02,  4.58457900e+00],
       [ 2.27092087e+02,  7.60758000e-01]])